[package]

name = "isovati"
version = "0.0.1"
authors = [ "Miikka Koskinen <miikka.koskinen@iki.fi>" ]

[[bin]]

name = "isovati"

[dependencies.openssl]

git = "https://github.com/sfackler/rust-openssl.git"

[dependencies.toml]

git = "https://github.com/alexcrichton/toml-rs"
